### PR TITLE
Homogeneous fund. theo. for symmetric polynomials

### PR DESCRIPTION
**Pull request by hivert**
Hi Pierre-Yves,

Here is an homogeneous version of the fundamental theorem for symmetric polynomial. Please tell me you are interested in merging it.

### CODE REVIEW

**Comment by hivert** [comment]
Here is a second change: the statements of `mprodXnE` and `mprodXE` are not general enough for my use case. Moreover, by generalizing the type of the input (any `finType` instead of `'I_n`), you get a simpler proof.

Note: I'm not completely fluent with github's pull-request workflow... I forgot to create a new branch on my repo, so that the two changes ended up in the same pull request though they are completely independent. Please tell me if you want two different pull requests.

**Comment by hivert** [comment]
I just realize that the finite hypothesis is not used at all.

**Comment by strub** [comment]
I've problems understanding this pull request. It seems that second commit is mostly reverting the first one.

**Comment by hivert** [comment]
Ok. It seems that I screwed up twith git's branches. I'm resubmitting two different pull requests:
-  	Homogeneous fund. theo. for symmetric polynomials
-  	Better mprodXnE and mprodXE

**Pull request closed without merging**
