### PR TITLE
add coq_makefile build method

### PR DESCRIPTION
**Pull request by haansn08**
Use the `coq_makefile` method which is [well documented](https://coq.inria.fr/distrib/current/refman/practical-tools/utilities.html?highlight=coq_makefile#building-a-coq-project-with-coq-makefile). This PR should fix both https://github.com/math-comp/multinomials/issues/58 and https://github.com/math-comp/multinomials/issues/75 .

### CODE REVIEW

**Review by strub — COMMENTED** [review]
Currently blocking the merge as installation works on my side.

**Comment by strub** [comment]
#65 should be merged first (this PR is also changing the logical name)

**Comment by haansn08** [comment]
I have merged #65 in this branch :)

**Comment by strub** [comment]
This is what I want to avoid :)

**Comment by strub** [comment]
#65 is now merged. I don't want to remove the `dune` build system. We can have both build in parallel though.

**Comment by haansn08** [comment]
I restored `dune-project` in this branch. Now both `dune build` and `make` as well as `make install` as described in the README work for me.

**Comment by pi8027** [comment]
@haansn08 The configure script has been removed in #79. Adding the option to use `coq_makefile` might be easier now. (If you still want to do so, please rebase this PR.)

**Pull request closed without merging**
