### PR TITLE
[coq] adapt to coq/coq#9995

### PR DESCRIPTION
**Pull request by proux01**
Make multinomials compile with current Coq master

### CODE REVIEW

**Comment by proux01** [comment]
Note: this only compiles with coq master and mathcomp master.

CI fails because this only compiles with coq-mathcomp-finmap.dev whereas the opam package for multinomials requires `"coq-mathcomp-finmap"    {>= "1.2.0" & < "1.3.0~"}`.

Also: do we want to make a branch "<= Coq 8.9" or go to some horrendous ltac to get something compiling with both coq <= 8.9 and master ?

**Comment by ggonthier** [comment]
Actually, there's some compatibility code in `mathcomp.ssr[eflect|fun|bool]` that ensures both MathComp and clients will compile with coq>=8.7, and likewise in `fin[map|set]` to ensure compilation with MathComp 1.8.0, so you only need to change the travis instructions to specify `finmap` `master`, and either specify `mathcomp` `master` or else duplicate the `{pred T}` `Notation` if you want 1.8.0 compatibility.

**Comment by proux01** [comment]
Nice, thanks, I'm looking at it.

**Comment by proux01** [comment]
Closing since coq-mathcomp-multinomials.1.3 is compatible with Coq master.

**Pull request closed without merging**
