### PR TITLE
Release 1.5.3

### PR DESCRIPTION
**Pull request by CohenCyril**

### CODE REVIEW

**Comment by strub** [comment]
Is there some documentation that explains the build workflow?

**Comment by CohenCyril** [comment]
> Is there some documentation that explains the build workflow?

https://github.com/coq-community/templates

**Comment by CohenCyril** [comment]
Maybe this stuff should self document itself though...

**Comment by CohenCyril** [comment]
@strub are you ok to merge as is?

**Comment by strub** [comment]
Currently, I am not able to regenerate the files. Which version of `mustache` are you using?

**Comment by CohenCyril** [comment]
I'm using `nix-shell -p mustache-go` on nix, which implementation did you try?

**Comment by strub** [comment]
The one in `opam`.

**Comment by CohenCyril** [comment]
Try `ruby-mustache` from debian/ubuntu's package managers (if that is your current linux distribution)

**Comment by strub** [comment]
I am on MacOS. It seems that the OCaml implementation of `mustache` does not support YAML as input format and brew does not have a `mustache/yaml` binary. It seems than on MacOS, we have to go on installing some implementation by hand. This seems sub-optimal :/

**Comment by CohenCyril** [comment]
@strub could you please open an issue on [coq-community/template](https://github.com/coq-community/templates/issues/new)

**Comment by strub** [comment]
I am now able to generate the build scripts. You can merge.

**Pull request closed without merging**
