### PR TITLE
Add coq-native support (if available) as per CEP 48

### PR DESCRIPTION
**Pull request by erikmd**
Subsumes and replaces PR https://github.com/math-comp/multinomials/pull/41

### CODE REVIEW

**Comment by erikmd** [comment]
> do you have a idea of what's missing?

On second thought I guess this is precisely what we had documented in this section:

https://github.com/coq/ceps/blob/master/text/048-packaging-coq-native.md#note-to-library-developers-and-package-maintainers

Roughly, in order to ensure that `coq-mathcomp-ssreflect` are native-compiled with Coq < 8.13, one should just apply the CEP 48 / item 3 strategy (given coq-mathcomp-ssreflect is built using coq_makefile) in the coq-opam-archive…

I'll try do to this soon.

Cc @proux01 @CohenCyril FYI

**Comment by proux01** [comment]
We can also just forget about Coq < 8.13 and coq-native, it would already be great to have things working with Coq >= 8.13. I'm not sure there are much users of Coq < 8.13 and native_compute around. native_compute with anything using multinomials is broken for more than six months now, having it work even with Coq >= 8.13 would be a huge progress.

**Comment by erikmd** [comment]
I see what you mean, but wouldn't it be a pity not to take advantage of coq-native for at least 8.12?
As the fix is simple and documented (item 3 of the CEP 48, which BTW should have been applicable just as well for Coq 8.5+).
Otherwise, if we give up this item-3 idea, this would strongly restrict the number of Coq versions we'll be able to compare for running ValidSDP benchmarks, for example.

Le 28 septembre 2021 08:49:09 GMT+02:00, Pierre Roux ***@***.***> a écrit :

**Comment by proux01** [comment]
I really don't care. My point is rather: don't put too much effort in supporting older versions as there isn't much use for it. Of course, if it's easy why not. But I'd really prefer something working with current versions to something not working at all.

**Comment by strub** [comment]
> I really don't care. My point is rather: don't put too much effort in supporting older versions as there isn't much use for it. Of course, if it's easy why not. But I'd really prefer something working with current versions to something not working at all.

Same for me.

**Comment by erikmd** [comment]
> I really don't care. My point is rather: don't put too much effort in supporting older versions as there isn't much use for it. Of course, if it's easy why not. But I'd really prefer something working with current versions to something not working at all.

OK. Regarding the effort involved, I'd say the vast majority of this effort is already done! (discussing and refining the CEP, preparing and merging the coq-native package, proposing a workflow to adapt packaging for both dune and coq_makefile).

Anyway, I agree with your pragmatism:
* Even if we could apply [`item 3`](https://github.com/coq/ceps/blob/master/text/048-packaging-coq-native.md#regarding-item-3) to *all* packages in a systematic way, it should be enough to apply it to a minimal set of dependencies (roughly, mathcomp.1.12.0) that is required for users to also benefit from `native_compute` in their (CoqEAL, Coq-8.12) based project;
* So FYI I've just opened this small PR: https://github.com/coq/opam-coq-archive/pull/1835
* But to avoid delaying the merge of this PR, I guess I will push a tiny extra commit that won't require having (coq.8.12, mathcomp.1.12.0, coq-native) working… but that we'll be able to trivially revert later on after the merge of [coq/opam-coq-archive#1835](https://github.com/coq/opam-coq-archive/pull/1835).

**Comment by erikmd** [comment]
> I will push a tiny extra commit that won't require having (coq.8.12, mathcomp.1.12.0, coq-native) working…

done. Does this look good to you?

**Comment by ejgallego** [comment]
@erikmd indeed that error usually happens when the native files for a depending library weren't compiled.

**Pull request merged**
